name = "aoe2backend-worker"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-10-20"
webpack_config = "webpack.config.js"
